version: '2'
services:
  server-1:
    image: clue/json-server
    ports:
      - 1111:80
    volumes:
      #- ./data1.json:/data/db.json
      - ./service1.js:/data/file.js
      - ./config/service1/:/data/config/service1/
  server-2:
    image: clue/json-server
    ports:
      - 2222:80
    volumes:
      #- ./data2.json:/data/db.json
      - ./service2.js:/data/file.js
      - ./config/service2/:/data/config/service2/
